CREATE DATABASE senai_roman_tarde

use senai_roman_tarde

CREATE TABLE CARGOS(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE EQUIPES(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(250) NOT NULL,
);

CREATE TABLE USUARIOS(
ID INT IDENTITY PRIMARY KEY,
ID_CARGO INT FOREIGN KEY REFERENCES CARGOS(ID) NOT NULL,
ID_EQUIPE INT FOREIGN KEY REFERENCES EQUIPES(ID) NOT NULL,
NOME VARCHAR(250) NOT NULL,
EMAIL VARCHAR(250) NOT NULL UNIQUE,
SENHA VARCHAR(250) NOT NULL
);

CREATE TABLE TEMAS(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(250) NOT NULL UNIQUE,
);

CREATE TABLE PROJETOS(
ID INT IDENTITY PRIMARY KEY,
ID_AUTOR INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL,
ID_TEMA INT FOREIGN KEY REFERENCES TEMAS(ID) NOT NULL,
NOME VARCHAR(250) NOT NULL,
);

select * from USUARIOS
select * from CARGOS
select * from PROJETOS
select * from TEMAS
select * from EQUIPES